apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: browser-service-dev
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infra-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/apps/browser-service/helm-chart
    repoURL: https://github.com/wermarter/diut
    targetRevision: develop
    helm:
      valueFiles:
        - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
