apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hcdc-web-app
  namespace: hcdc
spec:
  parentRefs:
    - kind: Gateway
      name: gateway-external
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - {{ .Values.hostname }}
  rules:
    - timeouts:
        request: "60s"
        backendRequest: "60s"
      matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hcdc-web-app
          port: 80
