name: update Helm image tag

on:
  workflow_call:
    inputs:
      values-path:
        required: true
        type: string
      identity:
        required: true
        type: string

jobs:
  helm-update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rebase
        run: git pull origin ${{github.ref_name}} --rebase

      - name: Edit values file
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = "${{ github.run_number }}"' ${{ inputs.values-path }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(helm): update image tag for ${{ inputs.identity }}'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
