apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "this.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - kind: Gateway
      name: gateway-internal
      namespace: envoy-gateway-system
      sectionName: grpc
  hostnames:
    - {{ .Values.hostname }}
  rules:
    - backendRefs:
        - name: {{ include "this.fullname" . }}
          port: 50051
      matches:
        - method:
            service: diut.BrowserService
            method: PrintMultiplePage
        - method:
            service: diut.BrowserService
            method: TestTimeout
        - method:
            service: diut.BrowserService
            method: TestError
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "this.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: {{ include "this.fullname" . }}
  loadBalancer:
    type: RoundRobin
  timeout:
    http:
      requestTimeout: "60s"